### ISSUE TITLE
Not working for latest version i.e. 1.45.1 of vscode

### ISSUE THREAD

**Issue by 4j4y** [oslabs-beta/Tropic#37]
I am not able to install this on the latest vscode version.

![image](https://user-images.githubusercontent.com/20925788/89600907-c9b95000-d880-11ea-9178-cd395177e276.png)

**Comment by joycelo** [comment]
Hi there!  Thank you for your post.  It looks like the alert message you posted indicates you are using VS Code version 1.45.1.  As the most recent version is 1.47.3, your VS Code may need to be updated to the current version for the extension to work.  If you choose to update, please feel free to let us know if you encounter any additional issues after doing so!
